name: Documentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq doxygen doxygen-doc doxygen-gui graphviz
    - name: Build Documentation
      run: |
        cd docs/Doxygen
        doxygen > doxygen.log
        ls
        ls ..
    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
        commit_message: 'Deploy code docs to GitHub Pages, Github Action id: $GITHUB_ACTION \nCommit: $GITHUB_SHA'
